export const ENDPOINTS = {
  AUTH: {
    SEND_OTP: "/auth/send-otp",
    LOGIN: "/auth/login",
    VERIFY_OTP: "/auth/verify-otp",
    RESEND_OTP: "/auth/resend-otp",
    LOGOUT: "/auth/logout",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    PROFILE: "/auth/profile",
    CHANGE_PASSWORD: "/auth/change-password",
    ME: "/auth/me",
    ADMIN_LOGIN: "/auth/admin/login",
  },
  USER: {
    PROFILE: "/user/profile",
  },
  PROVIDER: {
    LIST: "/provider/list",
    APPLY: "/provider/apply",
    PROFILE: "/provider/profile",
    RESET: "/provider/reset",
    ME_PROFILE: "/provider/me/profile",
    DETAILS: (id: string) => `/provider/${id}`,
  },
  JOB: {
    CREATE: "/job",
    MY: "/job/my",
    OFFERS: "/job/offers",
    AVAILABLE: "/job/availablejobs",
    DETAILS: (id: string) => `/job/${id}`,
    CANCEL: (id: string) => `/job/${id}/cancel`,
    ASSIGNMENTS: (id: string) => `/job/${id}/assignments`,
    ACCEPT: (id: string) => `/job/${id}/accept`,
    OFFER_ACCEPT: (id: string) => `/job/offers/${id}/accept`,
    OFFER_REJECT: (id: string) => `/job/offers/${id}/reject`,
  },
  ASSIGNMENT: {
    MY: "/assignment/my",
    DETAILS: (id: string) => `/assignment/${id}`,
    UPDATE_STATUS: (id: string) => `/assignment/${id}/status`,
    SUBMIT_PROOF: (id: string) => `/assignment/${id}/proof`,
    ABSENCE: (id: string) => `/assignment/${id}/absence`,
    MARK_PAID_CASH: (id: string) => `/assignment/${id}/payment/mark-as-paid-cash`,
    CONFIRM_CASH: (id: string) => `/assignment/${id}/payment/confirm-cash`,
    PROVIDER_MARK_PAID: (id: string) => `/assignment/${id}/payment/provider-mark-paid`,
    REJECT_PAYMENT: (id: string) => `/assignment/${id}/payment/reject`,
    CANCEL_BY_PROVIDER: (id: string) => `/assignment/${id}/cancel-by-provider`,
    CANCEL_BY_CLIENT: (id: string) => `/assignment/${id}/cancel-by-client`,
  },
  SKILLS: {
    ALL: "/skills/all",
    LIST: "/skills",
    MY: "/skills/my/skills",
  },
  LOCATION: {
    ALL: "/locations/all",
    LIST: "/locations",
    CREATE: "/locations",
  },
  MESSAGES: {
    GET_CONVERSATIONS: "/messages/getConversations",
    GET_MESSAGES: "/messages/getMessages",
    GET_CONVERSATION: "/messages/getConversation",
    CREATE: "/messages/createMessage",
    DELETE_CONVERSATION: "/messages/deleteConversation",
    DELETE_MESSAGE: "/messages/deleteMessage",
  },
  UPLOAD: {
    CHAT_IMAGE: "/upload/chat-image",
    SIGNATURE: "/upload/signature",
  },
  FINANCE: {
    WALLET_ME: "/wallet/me",
    WALLET_TRANSACTIONS: "/wallet/transactions",
    WALLET_ADMIN_OVERVIEW: "/wallet/admin/overview",
    PAYMENTS_ADMIN_EARNINGS: "/payments/admin/earnings",
    PAYMENTS_HISTORY_PROVIDER: "/payments/history/provider",
    PAYMENTS_CREATE_ORDER: "/payments/create-order",
    PAYMENTS_VERIFY: "/payments/verify",
    PAYMENTS_JOB_CREATE_ORDER: "/payments/job/create-order",
    PAYMENTS_JOB_VERIFY: "/payments/job/verify",
    PAYMENTS_CASH: (id: string) => `/payments/cash/${id}`,
    PAYMENTS_CONFIRM: (id: string) => `/payments/confirm/${id}`,
    PAYMENTS_REJECT: (id: string) => `/payments/reject/${id}`,
    PAYMENTS_HISTORY_ASSIGNMENT: (id: string) => `/payments/history/assignment/${id}`,
    INVOICES: "/invoices",
    INVOICE_DETAIL: (id: string) => `/invoices/${id}`,
    INVOICE_PDF: (id: string) => `/invoices/${id}/pdf`,
  },
  REVIEW: {
    ME: "/review/me",
    CREATE: "/review",
    USER: (id: string) => `/review/user/${id}`,
  },
  REPORT: {
    CREATE: "/report",
  },
  NOTIFICATION: {
    LIST: "/notifications",
    READ_ALL: "/notifications/read-all",
    READ_ONE: (id: string) => `/notifications/${id}/read`,
    DELETE: (id: string) => `/notifications/${id}`,
  },
  ADMIN: {
    PENDING_PROVIDERS: "/admin/providers/pending",
    USERS: "/admin/users",
    REPORTS: "/admin/reports",
    FINANCE_OVERVIEW: "/admin/finance/overview",
    FINANCE_TRANSACTIONS: "/admin/finance/transactions",
    APPROVE_PROVIDER: (id: string) => `/admin/provider/${id}/approve`,
    REJECT_PROVIDER: (id: string) => `/admin/provider/${id}/reject`,
    BLOCK_USER: (id: string) => `/admin/users/${id}/block`,
    PROVIDER_DETAILS: (id: string) => `/admin/provider/${id}`,
    USER_DETAILS: (id: string) => `/admin/user/${id}`,
    REPORT_DETAILS: (id: string) => `/admin/reports/${id}`,
    REPORT_ACTION: (id: string) => `/admin/reports/${id}/action`,
  },
  LANDING: "/landing",
};
