export const API_ROUTES = {
  BASE: "/api/v1",
  AUTH: "/auth",
  ADMIN: "/admin",
  PROVIDER: "/provider",
  SERVICE_REQUEST: "/service-request",
  LOCATIONS: "/locations",
  SKILLS: "/skills",
  UPLOAD: "/upload",
  LANDING: "/landing",
  JOB: "/job",
  ASSIGNMENT: "/assignment",
  MESSAGES: "/messages",
  REVIEW: "/review",
  REPORT: "/report",
  NOTIFICATIONS: "/notifications",
  PAYMENTS: "/payments",
  WALLET: "/wallet",
};